name: faceswap
channels:
  - conda-forge
  - apple
dependencies:
  - python>=3.8,<3.10
  - pip
  - tensorflow-deps==2.6.0
  - tk
  - libblas
  - pip:
    - tensorflow-macos
    - tensorflow-metal
    - tqdm>=4.62
    - psutil>=5.8.0
    - numpy>=1.18.0,<1.22.0
    - opencv-python>=4.5.3.0
    - pillow>=8.3.1
    - scikit-learn>=0.24.2
    - fastcluster>=1.1.26
    - matplotlib>=3.2.0,<3.3.0
    - imageio>=2.9.0
    - imageio-ffmpeg>=0.4.5
    - ffmpy==0.2.3